# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac0af18b27ac91067b2f554dec09e3d2a982358c5e16ace84b42ccae8fe952631454446cb8a8cb0ff3bad95075e33ce3a19181d1a581c3f8b529460064d659c3

test:
  secret_key_base: f50cfaedea3242e244e08dbfc960ec51074912c4556a59e13f28c3c70cf0984a86ab10459378558642aab4606004d52b020b520acadc0f8d78807fd9430c2b01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
